= Various crypto stuff

This project implements:

* an ASN.1 parser,
* a timestamp verifier
* an evidence record parser, and
* an evidence record verifier

Everything is pretty low level.
Sorry for that.
This parser has some advantages over other ASN.1 parsers.

- ASN.1 often contain other ASN.1 substructures like members of a list or even a string consisting of ASN.1 octets.
This parser tries hard to descend into such potential ASN.1 substructures and parses them as well.
- It ships a file `oid.properties` that provides human readable values for various oid keys. Do you have an ASN.1 file
that is not fully covered by this property file? Just add your missing properties and their human readable messages.
You have just created an even better ASN.1 parser!

How to use it:

[source]
----
java -jar crypto-misc.jar asn1 <fileName>
java -jar crypto-misc.jar er <erName> <certName> <dataName>
----

Please fetch a binary release from link:https://github.com/torstenwerner/crypto-misc/releases[github's release page].

== Continuous integration thanks to snap-ci.com

Build image:https://snap-ci.com/torstenwerner/crypto-misc/branch/master/build_image[status]
at link:https://snap-ci.com/torstenwerner/crypto-misc/branch/master[Snap CI]

== Searching a (e.g. timestamp) certificate by issuer DN and serial number

The following command might be useful in Germany.

[source]
----
ldapsearch -h ldap.nrca-ds.de -b 'dc=ldap,dc=nrca-ds,dc=de' -x '(&(x509issuer=CN=14R-CA 1:PN,o=Bundesnetzagentur,c=de)(x509serialNumber=960))'
----